name: fairy-bites
services:
- name: web
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
  build_command: npm run build
  run_command: npm start
  http_port: 3000
  instance_size_slug: basic-xxs
  instance_count: 1
  routes:
  - path: /
  env:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: 3000
  source_dir: /
  envs:
  - key: DO_NOT_TRACK
    value: "1"
  - key: DISABLE_STATIC_SITE
    value: "true"