name: fairy-bites
services:
- name: web
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
  build_command: npm run build
  run_command: npm start
  http_port: 3000
  routes:
  - path: /
  env:
  - key: NODE_ENV
    value: production